const { app, BrowserWindow, ipcMain, dialog, safeStorage, Menu, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const https = require('https');
const { spawn } = require('child_process');
const os = require('os');
const crypto = require('crypto');

// ─── Beta expiry ──────────────────────────────────────────────────────────────

const BETA_EXPIRES    = new Date("2026-09-01"); // Sept 1 — update per release
const IS_BETA_BUILD   = true;                   // set false for production builds

function checkBetaExpiry() {
  if (!IS_BETA_BUILD) return;
  if (new Date() < BETA_EXPIRES) return;

  dialog.showMessageBoxSync({
    type:    "error",
    title:   "Beta Expired",
    icon:    path.join(__dirname, "../build/icon.png"),
    message: "This beta build has expired.",
    detail:  [
      "Thank you for testing Tone Architect!",
      "",
      "This beta expired on " + BETA_EXPIRES.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }) + ".",
      "If you provided feedback, watch your email for your free permanent license.",
      "",
      "© 2026 Memo Gonzalez",
    ].join("\n"),
    buttons: ["OK"],
  });

  app.quit();
}

let llama      = null;   // Llama instance (v3 API)
let llamaModel = null;   // loaded model  (v3 API)

function getModelPath() {
  return path.join(app.getPath('userData'), 'models', 'llama3.1-8b.gguf');
}

function getModelsDir() {
  return path.join(app.getPath('userData'), 'models');
}

async function initializeLlama() {
  if (llamaModel) return true;

  const modelPath = getModelPath();
  if (!fs.existsSync(modelPath)) return false;

  try {
    // node-llama-cpp v3 is an ES module — must use dynamic import(), not require()
    const { getLlama } = await import('node-llama-cpp');
    if (!llama) llama = await getLlama();
    llamaModel = await llama.loadModel({ modelPath });
    console.log('[Llama] Model loaded successfully from', modelPath);
    return true;
  } catch (err) {
    console.error('[Llama] Failed to initialize:', err);
    llamaModel = null;
    llama      = null;
    return false;
  }
}

async function downloadLlamaModel(win) {
  const modelDir  = getModelsDir();
  const modelPath = getModelPath();

  if (!fs.existsSync(modelDir)) {
    fs.mkdirSync(modelDir, { recursive: true });
  }

  // Delete any existing corrupt/partial file
  if (fs.existsSync(modelPath)) fs.unlinkSync(modelPath);

  // Use node-llama-cpp's built-in downloader — handles HuggingFace LFS redirects,
  // auth headers, and partial-resume automatically.
  const { createModelDownloader } = await import('node-llama-cpp');

  const downloader = await createModelDownloader({
    modelUri: 'hf:bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf',
    dirPath:  modelDir,
    fileName: 'llama3.1-8b.gguf',
    onProgress({ downloadedSize, totalSize }) {
      const percent = totalSize > 0 ? Math.round((downloadedSize / totalSize) * 100) : 0;
      win.webContents.send('model-download-progress', {
        status:  `Downloading (${(downloadedSize / 1e9).toFixed(1)} GB / ${(totalSize / 1e9).toFixed(1)} GB)…`,
        percent: Math.min(percent, 99),
        done:    false,
      });
    },
  });

  await downloader.download();

  win.webContents.send('model-download-progress', {
    status:  'Download complete, initializing…',
    percent: 100,
    done:    true,
  });
}

// ─── Legal text ───────────────────────────────────────────────────────────────

const TERMS_OF_USE = `TONE ARCHITECT — TERMS OF USE & DISCLAIMER
© 2026 Memo Gonzalez. All rights reserved.
════════════════════════════════════════════

1. NO WARRANTY — USE AT YOUR OWN RISK
Tone Architect and all preset files it generates are provided "AS IS," without
warranty of any kind, express or implied, including but not limited to warranties
of merchantability, fitness for a particular purpose, or non-infringement.

Memo Gonzalez does not guarantee that generated presets will sound as expected,
match any specific tone, or be free of errors.

2. LIMITATION OF LIABILITY — GEAR & HEARING DAMAGE
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, MEMO GONZALEZ SHALL NOT BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES
ARISING FROM THE USE OF THIS SOFTWARE OR THE PRESETS IT GENERATES, INCLUDING BUT
NOT LIMITED TO: damage to audio equipment, speakers, amplifiers, hearing loss,
data loss, or loss of income.

You are solely responsible for the volume levels you set on your hardware and for
any use of the presets generated by this application.

3. THIRD-PARTY TRADEMARKS
Tone Architect is an independent software application and is NOT affiliated with,
endorsed by, or sponsored by Line 6, Inc. or Yamaha Corporation.

"Line 6," "HX Stomp," and "Helix" are registered trademarks of Line 6, Inc.
All other product names, trademarks, and registered trademarks are property of
their respective owners.

4. AI-GENERATED CONTENT
Presets are generated by a local AI model (Meta Llama). AI output may be
inaccurate, incomplete, or unsuitable for your specific hardware configuration.
Always review and adjust parameters before use. Never set extreme volumes without
first testing at low levels.

5. OPEN-SOURCE AI LICENSE
This application uses Meta's Llama model distributed under the Llama Community
License Agreement. Use of Llama is subject to Meta's Acceptable Use Policy.
For details: https://llama.meta.com/llama3/license/

Note: If Tone Architect ever reaches 700 million monthly active users, a separate
license from Meta will be required. We remain cautiously optimistic.

6. GOVERNING LAW
These terms are governed by applicable law. By using this software you agree to
these terms.`;

const USER_GUIDE = `TONE ARCHITECT — USER GUIDE
Created by Memo Gonzalez
════════════════════════════════

GETTING STARTED
───────────────
1. Make sure Ollama is running (look for the Ollama icon in your menu bar).
2. On first launch the app downloads the AI model (~5 GB, one-time only).
3. Type an artist, song, or describe a tone in the "Sonic Reference" field.
4. Click INITIALIZE SYNTHESIS and wait for the AI to generate your preset.
5. Click SAVE .HLX PRESET to download the file.
6. Import the .hlx file into HX Edit on your device.

IMPORTING YOUR PRESET
──────────────────────
Compatible device: Line 6 HX Stomp (firmware 3.7 and above).
• Connect your device via USB and open HX Edit.
• Go to File › Import › Preset… and select the .hlx file.
• If an import error appears, update your firmware to 3.7+ first.

MANUAL CONFIGURATION GUIDE
────────────────────────────
• Parameter values are shown on the 0–10 scale matching the device UI.
• Match each block and knob value exactly as displayed.
• Blocks are ordered by signal chain (left to right): drive → amp → cab → fx.

OPTIONAL UPLOADS
─────────────────
• Pedalboard photo: the AI skips effects you already own physically.
• Audio sample: provides a closer tonal reference for the AI.

TIPS
────
• Use the Cpu icon (top right) to reset the model at any time.
• Up to 6 DSP blocks are supported — presets are automatically capped.
• Start with low volume and adjust gradually after importing any preset.

ABOUT
─────
Tone Architect v1.5.0
© 2026 Memo Gonzalez

This software is not affiliated with, endorsed by, or sponsored by Line 6, Inc.
"Line 6" and "HX Stomp" are registered trademarks of Line 6, Inc.`;

const PARAM_GUIDE = `READING PARAMETER VALUES
─────────────────────────
Values in the Manual Configuration Guide use the same 0–10 scale as the device UI.

STANDARD PARAMETERS (0.0 – 10.0 range):
  Drive  5.0  →  set the Drive knob to 5.0
  Bass   6.0  →  set Bass to 6.0
  Mix    3.5  →  set Mix to 3.5
  Level  7.0  →  set Level to 7.0

SPECIAL PARAMETERS (natural units, enter as shown):
  LowCut  100   →  100 Hz
  HighCut 6000  →  6000 Hz
  Threshold -48 →  -48 dB

Always start with low output volume after importing a new preset.`;

// ─── Menu ─────────────────────────────────────────────────────────────────────

function buildMenu() {
  const template = [
    {
      label: app.name,
      submenu: [
        {
          label: 'About Tone Architect',
          click: () => {
            dialog.showMessageBox({
              type: 'info',
              title: 'About Tone Architect',
              message: 'Tone Architect',
              detail: [
                'Version 1.5.0',
                'Created by Memo Gonzalez',
                '© 2026 Memo Gonzalez',
                '',
                'AI-powered guitar preset generator.',
                'Compatible with Line 6 HX Stomp (firmware 3.7+).',
                'Runs 100% locally via Ollama — no cloud, no subscription.',
                '',
                'This app is NOT affiliated with, endorsed by, or sponsored by',
                'Line 6, Inc. or Yamaha Corporation.',
                '"Line 6" and "HX Stomp" are trademarks of Line 6, Inc.',
                '',
                'AI model: Meta Llama (Llama Community License).',
                'For license info: llama.meta.com/llama3/license',
              ].join('\n'),
              buttons: ['OK'],
            });
          },
        },
        { type: 'separator' },
        { role: 'services' },
        { type: 'separator' },
        { role: 'hide' },
        { role: 'hideOthers' },
        { role: 'unhide' },
        { type: 'separator' },
        { role: 'quit' },
      ],
    },
    {
      label: 'Edit',
      submenu: [
        { role: 'undo' },
        { role: 'redo' },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        { role: 'selectAll' },
      ],
    },
    {
      label: 'View',
      submenu: [
        { role: 'reload' },
        { role: 'forceReload' },
        { type: 'separator' },
        { role: 'resetZoom' },
        { role: 'zoomIn' },
        { role: 'zoomOut' },
        { type: 'separator' },
        { role: 'togglefullscreen' },
      ],
    },
    {
      label: 'Window',
      submenu: [
        { role: 'minimize' },
        { role: 'zoom' },
        { type: 'separator' },
        { role: 'front' },
      ],
    },
    {
      label: 'Help',
      submenu: [
        {
          label: 'User Guide',
          click: () => dialog.showMessageBox({
            type: 'info',
            title: 'Tone Architect — User Guide',
            message: 'User Guide',
            detail: USER_GUIDE,
            buttons: ['OK'],
          }),
        },
        {
          label: 'Parameter Scale Reference',
          click: () => dialog.showMessageBox({
            type: 'info',
            title: 'Parameter Scale Reference',
            message: 'Reading Parameter Values',
            detail: PARAM_GUIDE,
            buttons: ['OK'],
          }),
        },
        { type: 'separator' },
        {
          label: 'Terms of Use & Disclaimer',
          click: () => dialog.showMessageBox({
            type: 'info',
            title: 'Terms of Use & Disclaimer',
            message: 'Terms of Use',
            detail: TERMS_OF_USE,
            buttons: ['OK'],
          }),
        },
        { type: 'separator' },
        {
          label: 'Download HX Edit (Line 6)',
          click: () => shell.openExternal('https://line6.com/software/'),
        },
        {
          label: 'Download Ollama',
          click: () => shell.openExternal('https://ollama.com/download'),
        },
      ],
    },
  ];

  return Menu.buildFromTemplate(template);
}

// ─── Window ───────────────────────────────────────────────────────────────────

function getKeyPath() {
  return path.join(app.getPath('userData'), 'apikey.enc');
}

function createWindow() {
  const win = new BrowserWindow({
    width: 1280,
    height: 820,
    minWidth: 900,
    minHeight: 600,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  if (!app.isPackaged) {
    win.loadURL('http://localhost:5173');
  } else {
    win.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  return win;
}

// ─── IPC: Training-data consent ───────────────────────────────────────────────

function getConsentPath() {
  return path.join(app.getPath('userData'), 'consent.json');
}

ipcMain.handle('get-consent', () => {
  const p = getConsentPath();
  if (!fs.existsSync(p)) return null;        // null = never asked
  try { return JSON.parse(fs.readFileSync(p, 'utf8')).consent ?? null; }
  catch { return null; }
});

ipcMain.handle('set-consent', (_e, value) => {
  fs.writeFileSync(getConsentPath(), JSON.stringify({ consent: !!value }));
  return true;
});

// ─── IPC: API key ─────────────────────────────────────────────────────────────

ipcMain.handle('has-api-key', () => fs.existsSync(getKeyPath()));

ipcMain.handle('get-api-key', () => {
  const keyPath = getKeyPath();
  if (!fs.existsSync(keyPath)) return null;
  try {
    const buf = fs.readFileSync(keyPath);
    return safeStorage.isEncryptionAvailable()
      ? safeStorage.decryptString(buf)
      : buf.toString('utf8');
  } catch { return null; }
});

ipcMain.handle('set-api-key', (_e, apiKey) => {
  try {
    const data = safeStorage.isEncryptionAvailable()
      ? safeStorage.encryptString(apiKey)
      : Buffer.from(apiKey, 'utf8');
    fs.writeFileSync(getKeyPath(), data);
    return true;
  } catch { return false; }
});

ipcMain.handle('delete-api-key', () => {
  const keyPath = getKeyPath();
  if (fs.existsSync(keyPath)) fs.unlinkSync(keyPath);
});

// ─── IPC: Preset save dialog ──────────────────────────────────────────────────

ipcMain.handle('save-preset', async (_e, { filename, content }) => {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save Preset',
    defaultPath: path.join(app.getPath('documents'), filename),
    filters: [{ name: 'Guitar Preset', extensions: ['hlx'] }],
  });
  if (filePath) {
    fs.writeFileSync(filePath, content);
    return { success: true };
  }
  return { success: false };
});

// keep old IPC name working during transition
ipcMain.handle('save-helix-preset', async (_e, { filename, content }) => {
  const { filePath } = await dialog.showSaveDialog({
    title: 'Save Preset',
    defaultPath: path.join(app.getPath('documents'), filename),
    filters: [{ name: 'Guitar Preset', extensions: ['hlx'] }],
  });
  if (filePath) {
    fs.writeFileSync(filePath, content);
    return { success: true };
  }
  return { success: false };
});

// ─── IPC: Beta feedback ───────────────────────────────────────────────────────
// Paste your Google Apps Script Web App URL here after deploying it.
// Leave empty to silently skip submission during local development.
const FEEDBACK_ENDPOINT = "https://script.google.com/macros/s/AKfycbwhaQV805K3R3kw5uIvuKpwFg8kV8hvBCFh9tWBQ-4KAdlFJc9Cy-RjQeOtarz8_CU/exec";

// POST with redirect following — keeps POST method across all redirects
// (Google Apps Script 302s to script.googleusercontent.com but must stay POST)
function postWithRedirects(urlString, body, maxRedirects = 5) {
  return new Promise((resolve, reject) => {
    const attempt = (currentUrl, remaining) => {
      const url     = new URL(currentUrl);
      const module_ = url.protocol === 'https:' ? https : require('http');
      const options = {
        hostname: url.hostname,
        path:     url.pathname + url.search,
        method:   'POST',
        headers:  {
          'Content-Type':   'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
      };

      const req = module_.request(options, (res) => {
        console.log('[Feedback] HTTP', res.statusCode, currentUrl);
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          if (remaining <= 0) return reject(new Error('Too many redirects'));
          res.resume(); // drain before next request
          attempt(res.headers.location, remaining - 1);
          return;
        }
        let data = '';
        res.on('data', (chunk) => { data += chunk; });
        res.on('end', () => {
          console.log('[Feedback] Response:', data.slice(0, 200));
          resolve(data);
        });
      });

      req.on('error', reject);
      req.write(body);
      req.end();
    };

    attempt(urlString, maxRedirects);
  });
}

ipcMain.handle('submit-feedback', async (_e, payload) => {
  if (!FEEDBACK_ENDPOINT) return { success: false, reason: "no endpoint configured" };

  // Never include raw query text in training data unless user explicitly consented
  if (!payload.trainingConsent) {
    payload = { ...payload, query: "[redacted]", feedback: "[redacted]" };
  }

  try {
    const body = JSON.stringify(payload);
    const raw  = await postWithRedirects(FEEDBACK_ENDPOINT, body);
    try { return JSON.parse(raw); }
    catch { return { success: true }; }
  } catch (err) {
    console.error('[Feedback] Submit error:', err.message);
    return { success: false, reason: err.message };
  }
});

// ─── IPC: Llama model ─────────────────────────────────────────────────────────

ipcMain.handle('check-llama-ready', async () => {
  return await initializeLlama();
});

ipcMain.handle('check-model-available', () => {
  return fs.existsSync(getModelPath());
});

ipcMain.handle('download-model', async (_e) => {
  const win = BrowserWindow.getFocusedWindow();
  if (!win) throw new Error('No active window');

  try {
    await downloadLlamaModel(win);
    const ok = await initializeLlama();
    if (!ok) throw new Error('Model downloaded but failed to initialize. Please restart the app.');
    return true;
  } catch (err) {
    throw new Error(err instanceof Error ? err.message : 'Model download failed');
  }
});

ipcMain.handle('generate-preset', async (_e, { system, prompt, temperature, maxTokens }) => {
  if (!llamaModel) {
    throw new Error('Llama model not initialized. Please download the model first.');
  }

  let context;
  try {
    const { LlamaChatSession } = await import('node-llama-cpp');
    context = await llamaModel.createContext();
    const session = new LlamaChatSession({
      contextSequence: context.getSequence(),
      systemPrompt: system,
    });

    const response = await session.prompt(prompt, {
      temperature: temperature ?? 0.3,
      maxTokens:   maxTokens   ?? 4096,
    });

    return response;
  } catch (err) {
    throw new Error(err instanceof Error ? err.message : 'Model generation failed');
  } finally {
    if (context) await context.dispose();
  }
});

// ─── Bundled binary paths ─────────────────────────────────────────────────────

function getBinPath(name) {
  return app.isPackaged
    ? path.join(process.resourcesPath, 'bin', name)
    : path.join(__dirname, '..', 'resources', 'bin', name);
}

function getFfmpegPath() {
  const raw = require('ffmpeg-static');
  return app.isPackaged ? raw.replace('app.asar', 'app.asar.unpacked') : raw;
}

// ─── IPC: YouTube audio download ──────────────────────────────────────────────

ipcMain.handle('download-youtube-audio', async (_e, url) => {
  const ytdlp   = getBinPath('yt-dlp');
  const ffmpeg  = getFfmpegPath();
  const tmpFile = path.join(os.tmpdir(), `tone-analysis-${crypto.randomUUID()}.wav`);

  if (!fs.existsSync(ytdlp)) {
    throw new Error('yt-dlp binary not found. Please reinstall the app.');
  }

  await new Promise((resolve, reject) => {
    const proc = spawn(ytdlp, [
      '--extract-audio',
      '--audio-format', 'wav',
      '--audio-quality', '0',
      '--ffmpeg-location', ffmpeg,
      '--postprocessor-args', 'ffmpeg:-t 30 -ar 44100 -ac 1',
      '-o', tmpFile.replace('.wav', '.%(ext)s'),
      '--no-playlist',
      url,
    ]);

    let stderr = '';
    proc.stderr.on('data', (d) => { stderr += d.toString(); });
    proc.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`yt-dlp exited ${code}: ${stderr.slice(-300)}`));
    });
    proc.on('error', reject);
  });

  // yt-dlp may write .wav directly or as tmpFile without extension
  const outPath = fs.existsSync(tmpFile) ? tmpFile : tmpFile.replace('.wav', '.wav');

  if (!fs.existsSync(outPath)) {
    throw new Error('Audio download succeeded but output file not found.');
  }

  try {
    const buffer = fs.readFileSync(outPath);
    return buffer; // IPC serialises Buffer → Uint8Array on renderer side
  } finally {
    try { fs.unlinkSync(outPath); } catch { /* ignore */ }
  }
});

// ─── App lifecycle ────────────────────────────────────────────────────────────

function checkArchitecture() {
  if (os.arch() !== 'arm64') {
    dialog.showMessageBoxSync({
      type:    'error',
      title:   'Unsupported Architecture',
      message: 'Tone Architect requires Apple Silicon (M1 or later).',
      detail:  [
        'This app uses on-device AI inference with Apple Metal.',
        '',
        'Intel Macs are not supported — the AI model would run',
        'at CPU-only speed (5–10× slower), making it unusable.',
        '',
        'Please run Tone Architect on an M1, M2, M3, or M4 Mac.',
      ].join('\n'),
      buttons: ['OK'],
    });
    app.quit();
  }
}

let mainWindow;

app.whenReady().then(() => {
  checkArchitecture();      // exits immediately on Intel
  checkBetaExpiry();        // exits immediately if expired
  Menu.setApplicationMenu(buildMenu());
  mainWindow = createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) createWindow();
});
